spring:
  application:
    name: zuul-server
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    products:
      path : /products/**
      serviceId: products-micro-service
